### ISSUE TITLE
u256.fromBytes fails with out of memory error on bytes array

### ISSUE THREAD

**Issue by liquitious** [btc-vision/btc-runtime#39]
- works: `let latestRandomSeed: u256 = u256.fromU32(sha256(latestRandomSeed.toUint8Array())[0]);`
- works: `u256.fromBytes(latestRandomSeed.toUint8Array())` (where `latestRandomSeed` is `u256`)
- crashes: `u256.fromBytes(sha256(latestRandomSeed.toUint8Array()))`. both LE and BE fail with error: `[OPNetUnit HELP PANIC]: Error: out of memory`

Note that `sha256(latestRandomSeed.toUint8Array())` works and logging it I get something like: `109,8,85,163,53,128,47,11,194,9,70,243,196,140,5,182,185,140,20,181,120,2,13,95,66,161,102,185,127,230,245,159`

Easiest way to reproduce that shows issue is not related to `sha256`:
```ts
// this crashes with out of memory error!!
latestRandomSeed = u256.fromBytes([
                109, 8, 85, 163, 53, 128, 47, 11, 194, 9, 70, 243, 196, 140, 5, 182, 185, 140, 20,
                181, 120, 2, 13, 95, 66, 161, 102, 185, 127, 230, 245, 159,
            ] as u8[]);
```

even on an array of len 2 bytes or 4 bytes we get this same crash

**Comment by BlobMaster41** [comment]
Thanks for reporting. ill investigate

**Comment by BlobMaster41** [comment]
crashes: u256.fromBytes(sha256(latestRandomSeed.toUint8Array())). both LE and BE fail with error: [OPNetUnit HELP PANIC]: Error: out of memory

This means that your contract is using more memory that what you have specified. Are you using the asconfig file included in the project? This file set the memory at a maximum of 512 memory pages which equals to 32.768mb. This is the maximum a contract can consume.

If your memory is that high, your gas will be very high.

**Comment by liquitious** [comment]
Opened new issue here: #42
