### ISSUE TITLE
SafeMath.mod is inefficient and will lead to crashes when run with large numbers 

### ISSUE THREAD

**Issue by liquitious** [btc-vision/btc-runtime#42]
https://github.com/btc-vision/btc-runtime/blob/6375653d6b38dd75974bf1937aa385115d7d24ae/runtime/types/SafeMath.ts#L39

Compare this to how it is done in EVM: https://github.com/polynetwork/eth-contracts/blob/097214982454bb2e225c2bfba81d28f4852c2203/contracts/libs/math/SafeMath.sol#L154

I expect this will result in high fees/costs and if evm contracts are ported as-is this would result in unexpected behavior. eg the system we port does Safemath.mod on the output of sha256

Reproduce by trying: `SafeMath.mod(u256.from(Blockchain.timestamp)), u256.from(4));`

**Comment by BlobMaster41** [comment]
@impredmet

**Comment by impredmet** [comment]
i just submitted a PR that addresses this issue: #43
